### ISSUE TITLE
Update website methodology to account for data storage in the repo

### ISSUE THREAD

**Issue by thibaultmax** [urppchusj/impactpharmacie#7]
Update the methodology page on the website to reflect that:
1) The dataset is now "officially" stored as CSV files in the GitHub repo (under the `/data/second_gen` directory)
2) The spreadsheet now only contains ratings for the current week, other ratings will only be found in the CSV files in the repo.

**Comment by cynthiatanguay** [comment]
@thibaultmax website was updated today
